name: Daily Vocab Email

on:
  schedule:
    - cron: '0 14 * * *'   # every day at 14:00 UTC (9 AM CT)
  workflow_dispatch:        # allows you to trigger manually too

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run vocab mailer
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python vocab_mailer.py
